# Uncomment the next line to define a global platform for your project
# platform :ios, '13.1'

target 'DemoCourierApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoCourierApp

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Courier_iOS'

end
